version: 2
updates:
  - package-ecosystem: 'npm'
    cooldown:
      default-days: 7
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 7
    directory: '/'
    schedule:
      interval: 'daily'
    groups:
      octokit:
        patterns:
          - '@octokit*'
      css:
        patterns:
          - 'tailwind*'
          - '@tailwind*'
          - 'autoprefixer'
          - 'postcss*'
      plaiceholder:
        patterns:
          - 'plaiceholder'
          - '@plaiceholder*'
      shiki:
        patterns:
          - 'shiki'
          - '@shiki*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
  - package-ecosystem: 'github-actions'
    cooldown:
      default-days: 14
    directory: '/'
    schedule:
      interval: 'weekly'
