version: '3.9'

services:
  app:
    image: ghcr.io/timomeh/timomeh.de:latest
    build:
      context: .
      dockerfile: tools/Dockerfile
      target: runner
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
    env_file:
      - path: ./.env
        required: false
      - path: ./.env.local
        required: false
      - path: ./.env.production
        required: false
