version: '3.9'

services:
  app:
    image: ghcr.io/timomeh/timomeh.de:sqlite
    entrypoint:
      [
        'sh',
        '-c',
        'chown -R nextjs:nodejs /app/.next/cache/fetch-cache /app/db-data || true && su-exec nodejs node /app/server.js',
      ]
    healthcheck:
      test:
        - CMD-SHELL
        - |
          node -e "
            require('http').get('http://localhost:3000/-ah/up', res => {
              let data = '';
              res.on('data', chunk => data += chunk);
              res.on('end', () => {
                if (res.statusCode !== 200 || data.trim() !== 'OK') process.exit(1);
              });
            }).on('error', () => process.exit(1));
          "
      interval: 5s
      timeout: 2s
      retries: 12
    ports:
      - 3000:3000
    volumes:
      - fetch-cache:/app/.next/cache/fetch-cache
      - db-data:/app/db-data

  # starts on production, migrates the database, and then exits
  migrate:
    build:
      context: .
      dockerfile_inline: |
        FROM node:22-slim AS base
        ENV PNPM_HOME="/pnpm"
        ENV PATH="$PNPM_HOME:$PATH"
        COPY package.json ./
        RUN corepack enable && corepack prepare --activate
        WORKDIR /app

        FROM base AS deps
        COPY package.json pnpm-lock.yaml* .npmrc* ./
        RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

        FROM base
        COPY . .
        COPY --from=deps /app/node_modules /app/node_modules
        CMD ["pnpm", "drizzle-kit", "push", "--force"]
    restart: no
    depends_on:
      app:
        condition: service_healthy
    volumes:
      - db-data:/app/db-data/
