version: '3.9'

services:
  migrate:
    build:
      context: .
      dockerfile_inline: |
        FROM node:22-slim AS base
        ENV PNPM_HOME="/pnpm"
        ENV PATH="$PNPM_HOME:$PATH"
        COPY package.json ./
        RUN corepack enable && corepack prepare --activate
        WORKDIR /app

        FROM base AS deps
        COPY package.json pnpm-lock.yaml* .npmrc* ./
        RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

        FROM base
        COPY . .
        COPY --from=deps /app/node_modules /app/node_modules
        CMD ["pnpm", "drizzle-kit", "push", "--force"]
    restart: no
    volumes:
      - timomeh-de-blog-db:/app/db-data/

volumes:
  timomeh-de-blog-db:
