name: cache test
on:
  push:
    branches: ['cache-test']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Docker artifact cache
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            out/next-cache.tar
            out/pnpm-cache.tar
          key: ${{ runner.os }}-docker_arm64-next-pnpm-cache-${{ hashFiles('pnpm-lock.yaml', 'src/**/*.ts', 'src/**/*.tsx') }}
          restore-keys: ${{ runner.os }}-docker_arm64-next-pnpm-cache-

      - name: Build Next.js
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: false
          target: build
          build-args: |
            CACHE=${{ hashFiles('out/next-cache.tar', 'out/pnpm-cache.tar') == '' && 'uncached' || 'cached' }}

      - name: Export Cache
        uses: docker/build-push-action@v5
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: false
          target: export
          outputs: out
          build-args: |
            CACHE=${{ hashFiles('out/next-cache.tar', 'out/pnpm-cache.tar') == '' && 'uncached' || 'cached' }}

      - name: Create production runner
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CACHE=${{ hashFiles('out/next-cache.tar', 'out/pnpm-cache.tar') == '' && 'uncached' || 'cached' }}
