name: main
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  publish-release:
    runs-on: ubuntu-latest
    needs: ci
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    concurrency:
      group: deploy-production
    environment:
      name: production
      url: https://timomeh.de
    steps:
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3
      - uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp
      - run: docker load -i /tmp/docker-image.tar
      - name: publish
        run: docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      - name: release
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK }}' --header 'Authorization: Bearer ${{ secrets.COOLIFY_TOKEN }}'
